var eventBuilder = require('./event-builder');
var idGeneratorDate = require('./id-generator-date');
var inMemoryStore = require('./in-memory-store');
var _ = require('lodash');

module.exports = function(options){
  options = options || {};
  var store = options.store || inMemoryStore;
  var idGenerator = options.idGenerator || idGeneratorDate;
  var handlers = {};

  /*
  * Stores an event in underlying store
  * Events are always cloned to prevent accidental updates
  *
  * params: eventData => { 
  *     name - name of the event
  *     key - master key of the event (is sometimes called AggregateRootId)
  *     id - optional id, else generated by the idGenerator
  *     data - should be your eventdata/payload (but you can store it in any property you wish)  
  *    }
  */
  function storeEvent(eventData){
    var event = eventBuilder(eventData).withId(idGenerator).validate().build();
    store.save(event);
  }

  /*
  * Retrieve events stored in the master key (or AggregateRoot if you wish)
  * Events are always cloned to avoid accidental updates
  *
  * params : key => event master key
  */
  function getEventsFrom(key){
    return _.map(store.get(key), function(event){
      return _.cloneDeep(event);
    });
  }

  function getEvents(){
    return _.map(store.get(), function(event){
      return _.cloneDeep(event);
    });
  }

  /*
  * Register handler(s), function which is called when publishing an event 
  *
  * params : handler =>  { myHandler : function(){} }
  */
  function registerHandler(handler){
    _.extend(handlers, handler);
  }

  function getHandlers(){
    return _.cloneDeep(handlers);
  }

  function clearHandlers(){
    handlers = {};
  }

  return {
    add : storeEvent,
    clearHandlers : clearHandlers,
    getHandlers : getHandlers,
    getEventsFrom : getEventsFrom,
    getEvents : getEvents,
    registerHandler : registerHandler,
    setIdGenerator : function(generatorFn){ idGenerator = generatorFn; },
    setStore : function(store){ store = store; }
  };
};