var eventBuilder = require('./event-builder');
var idGeneratorDate = require('./id-generator-date');
var inMemoryStore = require('./in-memory-store');
var _ = require('lodash');

module.exports = function(options){
  options = options || {};
  var store = options.store || inMemoryStore;
  var idGenerator = options.idGenerator || idGeneratorDate;
  var handlers = {};

  if(options.clearStore && store.clear){
    store.clear();
  }

  /*
  * Stores an event in underlying store
  * Events are always cloned to prevent accidental updates
  *
  * params: eventData => { 
  *     name - name of the event
  *     key - master key of the event (is sometimes called AggregateRootId)
  *     id - optional id, else generated by the idGenerator
  *     data - should be your eventdata/payload (but you can store it in any property you wish)  
  *    }
  */
  function storeEvent(eventData){
    var event = eventBuilder(eventData).withId(idGenerator).validate().build();
    store.addEvent(event);
  }

  /*
  * Retrieve events stored in the master key (or AggregateRoot if you wish)
  * Events are always cloned to avoid accidental updates
  *
  * params : key => event master key
  */
  function getEventsFrom(key){
    return _.map(store.get(key), function(event){
      return _.cloneDeep(event);
    });
  }

  /*
  * Register handler(s), function which is called when publishing an event 
  *
  * params : handler =>  { myHandler : function(){} }
  */
  function registerHandler(handler){
    _.extend(handlers, handler);
  }

  function getHandlers(){
    return _.cloneDeep(handlers);
  }

  function clearHandlers(){
    handlers = {};
  }

  /*
  * Iterates through each stored event and applies corresponding event handler
  * Starts out to create an empty object and passing this through all event handlers
  * Returns build up object
  *
  * params: key => master key of eventstream
  *         from => (optional) int, starting point in event stream. Default = 0
  *         upTo => (optional) int, end point in event stream. Default = end of event list.
  *         domain => (optional) object to continue to apply events on.
  */
  function playEvents(key, from, upTo, domain){
    var events = getEventsFrom(key);
    var i = from || 0;
    upTo = upTo || events.length;
    domain = domain || {};

    for(; i < upTo; i++){
      if(!handlers[events[i].name]){
        throw 'Missing event handler for "' + events[i].name + '" in "' + key + '"';
      }
      handlers[events[i].name](events[i], domain);
    }
    return domain;
  }

  function publishEvent(eventData, snapShotKey){
    storeEvent(eventData);
    var domain = playEvents(eventData.key);
    addSnapshot(snapShotKey, domain);
  }

  function getSnapshot(key){
    return store.get(key);
  }

  function addSnapshot(key, data){
    store.save(key, data);
  }

  return {
    add : storeEvent,
    clearHandlers : clearHandlers,
    getHandlers : getHandlers,
    getEventsFrom : getEventsFrom,
    getSnapshot : getSnapshot,
    playEvents : playEvents,
    publishEvent : publishEvent,
    registerHandler : registerHandler,
    setIdGenerator : function(generatorFn){ idGenerator = generatorFn; },
    setStore : function(store){ store = store; }
  };
};